# Generated by Django 4.1.2 on 2022-10-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='statuses',
            field=models.ManyToManyField(blank=True, related_name='statuses', to='webapp.status', verbose_name='Status'),
        ),
    ]
